apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
